name = "MajorizationFigures"
uuid = "c27bb10a-d343-4c89-ac67-34093075c38a"
authors = ["Eric P. Hanson"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
